=== wendy48/ES2016_14353395/.local/share/Trash/files/dol/schema/processnetwork.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pn="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK" targetNamespace="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK"  elementFormDefault="qualified" >
  <xsd:include schemaLocation="generics.xsd"/>

  <xsd:element name="processnetwork">
    <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="variable" type="pn:variable" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="function" type="pn:function" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="process" type="pn:process" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="sw_channel" type="pn:sw_channel" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="iterator" type="pn:generaliterator" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="connection" type="pn:connection" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="configuration" type="pn:configuration" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="process">
    <xsd:complexContent>
      <xsd:extension base="pn:element">
        <xsd:sequence>
          <xsd:element name="append" type="pn:append" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:choice minOccurs="0">
            <xsd:sequence>
              <xsd:element name="iterator" type="pn:qualifiedportiterator" maxOccurs="unbounded"/>
              <xsd:element name="port" type="pn:qualifiedport" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:element name="port" type="pn:qualifiedport" maxOccurs="unbounded"/>
          </xsd:choice>
          <xsd:element name="source" type="pn:source"/>
          <xsd:element name="configuration" type="pn:configuration" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="source">
    <xsd:attribute name="type" use="required">
      <xsd:simpleType>
        <xsd:restriction base="xsd:string">
          <xsd:enumeration value="c"/>
          <xsd:enumeration value="c++"/>
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
    <xsd:attribute name="location" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="sw_channel">
    <xsd:complexContent>
      <xsd:extension base="pn:element">
        <xsd:sequence>
          <xsd:element name="append" type="pn:append" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="port" type="pn:qualifiedport" minOccurs="2" maxOccurs="2"/>
          <xsd:element name="configuration" type="pn:configuration" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="size" type="xsd:string" use="required"/>
        <xsd:attribute name="tokensize" type="xsd:string" default="1" use="optional"/>
        <xsd:attribute name="type" use="required">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="fifo"/>
              <xsd:enumeration value="wfifo"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="port">
    <xsd:complexContent>
      <xsd:extension base="pn:element">
        <xsd:sequence>
          <xsd:element name="append" type="pn:append" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="qualifiedport">
    <xsd:complexContent>
      <xsd:extension base="pn:port">
        <xsd:attribute name="type" use="required">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="input"/>
              <xsd:enumeration value="output"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="connection">
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="append" type="pn:append" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="origin" type="pn:connector"/>
      <xsd:element name="target" type="pn:connector"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="connector">
    <xsd:sequence>
      <xsd:element name="append" type="pn:append" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="port" type="pn:port"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>
  
  <xsd:complexType name="generaliterator">
    <xsd:complexContent>
      <xsd:extension base="pn:iterator">
        <xsd:sequence>
          <xsd:element name="iterator" type="pn:generaliterator" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="process" type="pn:process" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="sw_channel" type="pn:sw_channel" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="connection" type="pn:connection" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="qualifiedportiterator">
    <xsd:complexContent>
      <xsd:extension base="pn:iterator">
        <xsd:choice>
          <xsd:sequence>
            <xsd:element name="iterator" type="pn:qualifiedportiterator" maxOccurs="unbounded"/>
            <xsd:element name="port" type="pn:qualifiedport" minOccurs="0" maxOccurs="unbounded"/>
          </xsd:sequence>
          <xsd:element name="port" type="pn:qualifiedport" maxOccurs="unbounded"/>
        </xsd:choice>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

</xsd:schema>

=== wendy48/ES2016_14353395/.local/share/Trash/files/dol/examples/example8/example8.xml
<?xml version="1.0" encoding="UTF-8"?>
<processnetwork xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK
http://www.tik.ee.ethz.ch/~shapes/schema/processnetwork.xsd" name="example8"> 

  <!-- processes -->
  <process name="producer"> 
    <port type="output" name="A"/>
    <port type="output" name="B"/>
     <source type="c" location="producer.c"/>
  </process>

  <process name="consumer"> 
    <port type="input" name="A"/> 
       <port type="input" name="B"/>
    <source type="c" location="consumer.c"/>
  </process>


  <!-- sw_channels -->
  <sw_channel type="fifo" size="10" name="C1">
    <port type="input" name="in"/>
    <port type="output" name="out"/>
  </sw_channel>

  <sw_channel type="fifo" size="10" name="C2">
    <port type="input" name="in"/>
    <port type="output" name="out"/>
  </sw_channel>

  <!-- connections -->
  <connection name="p-c1-a">
    <origin name="producer">
      <port name="A"/>
    </origin>
    <target name="C1">
      <port name="in"/>
    </target>
  </connection>

  <connection name="p-c1-b">
    <origin name="producer">
      <port name="B"/>
    </origin>
    <target name="C2">
      <port name="in"/>
    </target>
  </connection>

  <connection name="c-c1-a">
    <origin name="C1">
      <port name="out"/>
    </origin>
    <target name="consumer">
      <port name="A"/>
    </target>
  </connection>

  <connection name="c-c2-b">
    <origin name="C2">
     <port name="out"/>
    </origin>
    <target name="consumer">
      <port name="B"/>
    </target>
  </connection>

</processnetwork>

=== wendy48/ES2016_14353395/.local/share/Trash/files/dol/examples/example1/example1.xml
<?xml version="1.0" encoding="UTF-8"?>
<processnetwork 
xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK
    http://www.tik.ee.ethz.ch/~shapes/schema/processnetwork.xsd" name="example1"> 

  <!-- processes -->
  <process name="generator"> 
    <port type="output" name="1"/>
    <source type="c" location="generator.c"/>
  </process>

  <process name="consumer"> 
    <port type="input" name="1"/> 
    <source type="c" location="consumer.c"/>
  </process>

  <process name="square"> 
    <port type="input" name="1"/>
    <port type="output" name="2"/>
    <source type="c" location="square.c"/>
  </process>

  <!-- sw_channels -->
  <sw_channel type="fifo" size="10" name="C1">
    <port type="input" name="0"/>
    <port type="output" name="1"/>
  </sw_channel>

  <sw_channel type="fifo" size="10" name="C2">
    <port type="input" name="0"/>
    <port type="output" name="1"/>
  </sw_channel>

  <!-- connections -->
  <connection name="g-c">
    <origin name="generator">
      <port name="1"/>
    </origin>
    <target name="C1">
      <port name="0"/>
    </target>
  </connection>

  <connection name="c-c">
    <origin name="C2">
      <port name="1"/>
    </origin>
    <target name="consumer">
      <port name="1"/>
    </target>
  </connection>

  <connection name="s-c">
    <origin name="square">
      <port name="2"/>
    </origin>
    <target name="C2">
      <port name="0"/>
    </target>
  </connection>

  <connection name="c-s">
    <origin name="C1">
      <port name="1"/>
    </origin>
    <target name="square">
      <port name="1"/>
    </target>
  </connection>

</processnetwork>

=== wendy48/ES2016_14353395/dol/build/bin/main/example1/example1_flattened.xml
<?xml version="1.0" encoding="UTF-8"?>
<processnetwork xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK     http://www.tik.ee.ethz.ch/~shapes/schema/processnetwork.xsd" name="example1_flattened">
 
<process name="generator" basename="generator">
  <port name="1" type="output" basename="1"/>
  <source location="generator.c" type="c"/>
</process>
<process name="consumer" basename="consumer">
  <port name="1" type="input" basename="1"/>
  <source location="consumer.c" type="c"/>
</process>
<process name="square" basename="square">
  <port name="1" type="input" basename="1"/>
  <port name="2" type="output" basename="2"/>
  <source location="square.c" type="c"/>
</process>
<sw_channel name="C1" type="fifo" size="10" basename="C1">
  <port name="0" type="input" basename="0"/>
  <port name="1" type="output" basename="1"/>
</sw_channel>
<sw_channel name="C2" type="fifo" size="10" basename="C2">
  <port name="0" type="input" basename="0"/>
  <port name="1" type="output" basename="1"/>
</sw_channel>
<connection name="g-c">
  <origin name="generator">
    <port name="1"/>
  </origin>
  <target name="C1">
    <port name="0"/>
  </target>
</connection>
<connection name="c-c">
  <origin name="C2">
    <port name="1"/>
  </origin>
  <target name="consumer">
    <port name="1"/>
  </target>
</connection>
<connection name="s-c">
  <origin name="square">
    <port name="2"/>
  </origin>
  <target name="C2">
    <port name="0"/>
  </target>
</connection>
<connection name="c-s">
  <origin name="C1">
    <port name="1"/>
  </origin>
  <target name="square">
    <port name="1"/>
  </target>
</connection>
</processnetwork>

=== wendy48/ES2016_14353395/dol/examples/example3/example3.xml
<?xml version="1.0" encoding="UTF-8"?>
<processnetwork xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK
http://www.tik.ee.ethz.ch/~shapes/schema/processnetwork.xsd" name="example3">

  <variable value="3" name="N"/>
  <variable value="10" name="FIFO_SIZE"/>

  <!-- instantiate resources -->
  <iterator variable="i" range="N">
    <process name="horizontal_generator">
      <append function="i"/> 
      <port type="output" name="h_out"/>
      <source type="c" location="horizontal_generator.c"/>
    </process>
     <process name="horizontal_consumer">
      <append function="i"/> 
      <port type="input" name="h_in"/>
      <source type="c" location="horizontal_consumer.c"/>
    </process>
  </iterator>

  <iterator variable="i" range="N">
    <process name="vertical_generator">
      <append function="i"/>
      <port type="output" name="v_out"/>
      <source type="c" location="vertical_generator.c"/>
    </process>
     <process name="vertical_consumer">
      <append function="i"/>
      <port type="input" name="v_in"/>
      <source type="c" location="vertical_consumer.c"/>
    </process>
  </iterator>
  
  <iterator variable="i" range="N">
    <iterator variable="j" range="N">
      <process name="forward">
        <append function="i"/>
        <append function="j"/>
        <port type="input" name="west"/>
        <port type="input" name="north"/>
        <port type="output" name="east"/>
        <port type="output" name="south"/>
        <source type="c" location="forward.c"/>
      </process>
    </iterator>
  </iterator>
  
  <iterator variable="i" range="N + 1">
    <iterator variable="j" range="N">
      <sw_channel type="fifo" size="FIFO_SIZE" name="C_h">
        <append function="i"/>
        <append function="j"/>
        <port type="input" name="in"/>
        <port type="output" name="out"/>
      </sw_channel>
      <sw_channel type="fifo" size="FIFO_SIZE" name="C_v">
        <append function="j"/>
        <append function="i"/>
        <port type="input" name="in"/>
        <port type="output" name="out"/>
      </sw_channel>
    </iterator>
  </iterator>

  <!-- instantiate connections -->
  <iterator variable="i" range="N">
    <iterator variable="j" range="N">
      <connection name="west">
        <append function="i"/>
        <append function="j"/>
        <origin name="C_h">
          <append function="i"/>
          <append function="j"/>
          <port name="out"/>
        </origin>
        <target name="forward">
           <append function="i"/>
           <append function="j"/>
           <port name="west"/>
         </target>
      </connection>
      
      <connection name="east">
        <append function="i"/>
        <append function="j"/>
        <origin name="forward">
          <append function="i"/>
          <append function="j"/>
          <port name="east"/>
        </origin>
        <target name="C_h">
           <append function="i + 1"/>
           <append function="j"/>
           <port name="in"/>
         </target>
      </connection>
            
      <connection name="north">
        <append function="i"/>
        <append function="j"/>
        <origin name="C_v">
          <append function="i"/>
          <append function="j"/>
          <port name="out"/>
        </origin>
        <target name="forward">
           <append function="i"/>
           <append function="j"/>
           <port name="north"/>
         </target>
      </connection>
      
      <connection name="south">
        <append function="i"/>
        <append function="j"/>
        <origin name="forward">
          <append function="i"/>
          <append function="j"/>
          <port name="south"/>
        </origin>
        <target name="C_v">
           <append function="i"/>
           <append function="j + 1"/>
           <port name="in"/>
         </target>
      </connection>
    </iterator>
  </iterator>
  
  <!-- boundary connections -->
  <iterator variable="i" range="N">
    <connection name="west">
      <append function="i + 1"/>
      <origin name="horizontal_generator">
        <append function="i"/>
        <port name="h_out"/>
      </origin>
      <target name="C_h">
         <append function="0"/>
         <append function="i"/>
         <port name="in"/>
       </target>
    </connection>

    <connection name="east">
      <append function="i + 1"/>
      <origin name="C_h">
         <append function="N"/>
         <append function="i"/>
         <port name="out"/>
      </origin>
      <target name="horizontal_consumer">
         <append function="i"/>
         <port name="h_in"/>
       </target>
    </connection>

    <connection name="north">
      <append function="i + 1"/>
      <origin name="vertical_generator">
        <append function="i"/>
        <port name="v_out"/>
      </origin>
      <target name="C_v">
         <append function="i"/>
         <append function="0"/>
         <port name="in"/>
       </target>
    </connection>

    <connection name="south">
      <append function="i + 1"/>
      <origin name="C_v">
         <append function="i"/>
         <append function="N"/>
         <port name="out"/>
      </origin>
      <target name="vertical_consumer">
         <append function="i"/>
         <port name="v_in"/>
       </target>
    </connection>
  </iterator>

</processnetwork>

=== wendy48/ES2016_14353395/dol/examples/examplecell/examplecell.xml
<?xml version="1.0" encoding="UTF-8"?>
<processnetwork xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK
http://www.tik.ee.ethz.ch/~shapes/schema/processnetwork.xsd" name="example2"> 

  <variable value="9" name="N"/>


  <!-- instantiate resources -->
  <process name="generator">
    <port type="output" name="10"/>
    <source type="c" location="generator.c"/>
  </process>

  <iterator variable="i" range="N">
    <process name="square">
      <append function="i"/>
      <port type="input" name="0"/>
      <port type="output" name="1"/>
      <source type="c" location="square.c"/>
    </process>
  </iterator>

  <process name="consumer">
    <port type="input" name="100"/>
    <source type="c" location="consumer.c"/>
  </process>

  <iterator variable="i" range="N + 1">
    <sw_channel type="fifo" size="10" name="C2">
      <append function="i"/>
      <port type="input" name="0"/>
      <port type="output" name="1"/>
    </sw_channel>
  </iterator>

  <!-- instantiate connection -->
  <iterator variable="i" range="N">
    <connection name="to_square">
      <append function="i"/>
      <origin name="C2">
        <append function="i"/>
        <port name="1"/>
      </origin>
      <target name="square">
        <append function="i"/>
        <port name="0"/>
      </target>
    </connection>

    <connection name="from_square">
        <append function="i"/>
        <origin name="square">
          <append function="i"/>
          <port name="1"/>
        </origin>
        <target name="C2">
          <append function="i + 1"/>
          <port name="0"/>
        </target>
    </connection>
  </iterator>

  <connection name="g_">
    <origin name="generator">
     <port name="10"/>
    </origin>
    <target name="C2"> 
      <append function="0"/>
      <port name="0"/>
    </target>
  </connection>

  <connection name="_c">
    <origin name="C2">
      <append function="N"/>
      <port name="1"/>
    </origin>
    <target name="consumer">
      <port name="100"/>
    </target>
  </connection>

</processnetwork>

=== wendy48/ES2016_14353395/.local/share/Trash/files/dol/examples/example7/example7.xml
<?xml version="1.0" encoding="UTF-8"?>
<processnetwork xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/PROCESSNETWORK
http://www.tik.ee.ethz.ch/~shapes/schema/processnetwork.xsd" name="filter">

  <!-- N - 1 is the filter order -->
  <variable name="N" value="3"/>

  <!-- instantiate processes -->
  <process name="producer">
    <port type="output" name="out"/>
    <source type="c" location="producer.c"/>
  </process>

  <process name="consumer">
    <port type="input" name="in"/>
    <source type="c" location="consumer.c"/>
  </process>

  <iterator  variable="i" range="N">
    <process name="filter">
      <append function="i"/>
      <port type="input" name="inA"/>
      <port type="input" name="inB"/>
      <port type="output" name="outA"/>
      <port type="output" name="outB"/>
      <source type="c" location="filter.c"/>
    </process>
  </iterator>
  
  <!-- instantiate sw_channels -->
  <sw_channel type="fifo" size="4" name="inputchannel">
    <port type="input" name="in"/>
    <port type="output" name="out"/>
  </sw_channel>

  <sw_channel type="fifo" size="4" name="outputchannel">
    <port type="input" name="in"/>
    <port type="output" name="out"/>
  </sw_channel>
  
  <iterator  variable="i" range="N - 1">  
    <sw_channel type="fifo" size="4" name="filterchannelA">
      <append function="i"/>
      <port type="input" name="in"/>
      <port type="output" name="out"/>
    </sw_channel>

    <sw_channel type="fifo" size="4" name="filterchannelB">
      <append function="i"/>
      <port type="input" name="in"/>
      <port type="output" name="out"/>
    </sw_channel>
  </iterator>
  
  <sw_channel type="fifo" size="4" name="feedbackchannel">
    <port type="input" name="in"/>
    <port type="output" name="out"/>
  </sw_channel>

  <!-- connections of top filter stage -->
  <connection name="inputconnection">
    <origin name="producer">
      <port name="out"/>
    </origin>
    <target name="inputchannel">
      <port name="in"/>
    </target>
  </connection>

  <connection name="outputconnection">
    <origin name="outputchannel">
      <port name="out"/>
    </origin>
    <target name="consumer">
      <port name="in"/>
    </target>
  </connection>
  
  <connection name="filterconnectionin">
    <origin name="inputchannel">
      <port name="out"/>
    </origin>
    <target name="filter">
      <append function="0"/>
      <port name="inA"/>
    </target>
  </connection>

  <connection name="filterconnectionout">
    <origin name="filter">
      <append function="0"/>
      <port name="outB"/>
    </origin>
    <target name="outputchannel">
      <port name="in"/>
    </target>
  </connection>

  <!-- connections of intermediate filter stage(s) -->  
  <iterator  variable="i" range="N - 1">  
    <connection name="filterconnectionoutAinA1">
      <append function="i"/>
      <origin name="filter">
        <append function="i"/>
        <port name="outA"/>
      </origin>
      <target name="filterchannelA">
        <append function="i"/>
        <port name="in"/>
      </target>
    </connection>
 
    <connection name="filterconnectionoutAinA2">
      <append function="i"/>
      <origin name="filterchannelA">
        <append function="i"/>
        <port name="out"/>
      </origin>
      <target name="filter">
        <append function="i + 1"/>
        <port name="inA"/>
      </target>
    </connection>

    <connection name="filterconnectionoutBinB1">
      <append function="i"/>
      <origin name="filter">
        <append function="i + 1"/>
        <port name="outB"/>
      </origin>
      <target name="filterchannelB">
        <append function="i"/>
        <port name="in"/>
      </target>
    </connection>
 
    <connection name="filterconnectionoutBinB2">
      <append function="i"/>
      <origin name="filterchannelB">
        <append function="i"/>
        <port name="out"/>
      </origin>
      <target name="filter">
        <append function="i"/>
        <port name="inB"/>
      </target>
    </connection>
  </iterator>
  
  <!-- connection of bottom filter stage -->
  <connection name="sinkconnectionA1">
    <origin name="filter">
      <append function="N - 1"/>
      <port name="outA"/>
    </origin>
    <target name="feedbackchannel">
      <port name="in"/>
    </target>
  </connection>
  
  <connection name="sinkconnectionA2">
    <origin name="feedbackchannel">
      <port name="out"/>
    </origin>
    <target name="filter">
      <append function="N - 1"/>
      <port name="inB"/>
    </target>
  </connection>
</processnetwork>
