=== wendy48/ES2016_14353395/dol/schema/architecture.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:arch="http://www.tik.ee.ethz.ch/~shapes/schema/ARCHITECTURE" targetNamespace="http://www.tik.ee.ethz.ch/~shapes/schema/ARCHITECTURE" elementFormDefault="qualified">
  <xsd:include schemaLocation="generics.xsd"/>

  <xsd:element name="architecture">
    <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="variable" type="arch:variable" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="function" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="processor" type="arch:processor" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="memory" type="arch:memory" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="hw_channel" type="arch:hw_channel" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="iterator" type="arch:generaliterator" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="readpath" type="arch:readpath" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="writepath" type="arch:writepath" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="processor">
    <xsd:complexContent>
      <xsd:extension base="arch:resource">
        <xsd:attribute name="type" use="required">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="RISC"/>
              <xsd:enumeration value="DSP"/>
              <xsd:enumeration value="POT"/>
              <xsd:enumeration value="NETSIM"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="memory">
    <xsd:complexContent>
      <xsd:extension base="arch:resource">
        <xsd:attribute name="type" use="required">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="ROM"/>
              <xsd:enumeration value="RAM"/>
              <xsd:enumeration value="REG"/>
              <xsd:enumeration value="DXM"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="hw_channel">
    <xsd:complexContent>
      <xsd:extension base="arch:resource">
        <xsd:attribute name="type" use="required">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="FIFO"/>
              <xsd:enumeration value="BUS"/>
              <xsd:enumeration value="DMA"/>
              <xsd:enumeration value="SPI"/>
              <xsd:enumeration value="BRIDGE"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="resource">
    <xsd:complexContent>
      <xsd:extension base="arch:element">
        <xsd:sequence>
          <xsd:element name="append" type="arch:append" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="configuration" type="arch:configuration" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="writepath">
    <xsd:sequence minOccurs="1" maxOccurs="1">
      <xsd:element name="append" type="arch:append" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="processor" type="arch:resourcereference" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="txbuf" type="arch:resourcereference" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="hw_channel" type="arch:resourcereference" minOccurs="1" maxOccurs="unbounded"/>
      <xsd:element name="chbuf" type="arch:resourcereference" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="configuration" type="arch:configuration" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="readpath">
    <xsd:sequence minOccurs="1" maxOccurs="1">
      <xsd:element name="append" type="arch:append" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="processor" type="arch:resourcereference" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="chbuf" type="arch:resourcereference" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="hw_channel" type="arch:resourcereference" minOccurs="1" maxOccurs="unbounded"/>
      <xsd:element name="rxbuf" type="arch:resourcereference" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="configuration" type="arch:configuration" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="resourcereference">
    <xsd:sequence>
      <xsd:element name="append" type="arch:append" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="generaliterator">
    <xsd:complexContent>
      <xsd:extension base="arch:iterator">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">
          <xsd:element name="readpath" type="arch:readpath" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="writepath" type="arch:writepath" minOccurs="0" maxOccurs="unbounded"/>	
          <xsd:element name="processor" type="arch:processor" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="memory" type="arch:memory" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="hw_channel" type="arch:hw_channel" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="iterator" type="arch:generaliterator" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

</xsd:schema>

=== wendy48/ES2016_14353395/.local/share/Trash/files/dol/examples/examplecell/cell.xml
<?xml version="1.0" encoding="UTF-8"?>
<architecture xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/ARCHITECTURE"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/ARCHITECTURE
                      http://www.tik.ee.ethz.ch/~shapes/schema/architecture.xsd"
  name="Sony/Toshiba/IBM Cell Broadband Engine architecture">

  <processor name="ppu" type="RISC">
  </processor>
  
  <processor name="spu_0" type="DSP">
  </processor>

  <processor name="spu_1" type="DSP">
  </processor>
  
  <processor name="spu_2" type="DSP">
  </processor>
  
  <processor name="spu_3" type="DSP">
  </processor>
  
  <processor name="spu_4" type="DSP">
  </processor>
  
  <processor name="spu_5" type="DSP">
  </processor>
  
</architecture>

=== wendy48/ES2016_14353395/.local/share/Trash/files/dol/examples/arch/vsp.xml
<?xml version="1.0" encoding="UTF-8"?>
<architecture xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/ARCHITECTURE"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/ARCHITECTURE
                      http://www.tik.ee.ethz.ch/~shapes/schema/architecture.xsd"
  name="SHAPES tile">

  <!-- arm subsystem -->
  <processor name="ARM" type="RISC">
    <configuration name="memory" value="rdm"/>
  </processor>
  
  <memory name="rdm" type="RAM">
  </memory>

  <hw_channel name="armbus" type="BUS">
    <configuration name="frequency" value="100000000"/>
    <configuration name="bytespercycle" value="1"/>
  </hw_channel>
  
  <!-- magic subsystem -->
  <processor name="MAGIC" type="DSP">
    <configuration name="memory" value="ddm"/>
  </processor>

  <memory name="ddm" type="RAM">
  </memory>

  <hw_channel name="magicbus" type="BUS">
    <configuration name="frequency" value="100000000"/>
    <configuration name="bytespercycle" value="1"/>
  </hw_channel>
  
  <hw_channel name="dma" type="DMA">
    <configuration name="frequency" value="100000000"/>
    <configuration name="bytespercycle" value="1"/>
  </hw_channel>

  <!-- distributed external memory -->
  <memory name="dxm" type="DXM">
  </memory>

  <!-- ssc subsystem -->
  <processor name="SSC" type="POT">
    <configuration name="memory" value="sscreg"/>
  </processor>
  
  <memory name="sscreg" type="RAM">
  </memory>

  <!-- ahb multi-layered bus -->
  <hw_channel name="ahb0" type="BUS">
    <configuration name="frequency" value="100000000"/>
    <configuration name="bytespercycle" value="1"/>
  </hw_channel>

  <hw_channel name="ahb1" type="BUS">
    <configuration name="frequency" value="100000000"/>
    <configuration name="bytespercycle" value="1"/>
  </hw_channel>

  <hw_channel name="ahb2" type="BUS">
    <configuration name="frequency" value="100000000"/>
    <configuration name="bytespercycle" value="1"/>
  </hw_channel>


  <!-- arm paths -->
  <writepath name="rdmdxm">
    <processor name="ARM"/>
    <txbuf name="rdm"/>
    <hw_channel name="armbus"/>
    <hw_channel name="ahb1"/>
    <chbuf name="dxm"/>
    <configuration name="delay" value="0"/>
    <configuration name="cycles" value="8"/>
  </writepath>
  
  <readpath name="dxmrdm">
    <processor name="ARM"/>
    <chbuf name="dxm"/>
    <hw_channel name="ahb1"/>
    <hw_channel name="armbus"/>
    <rxbuf name="rdm"/>
    <configuration name="delay" value="0"/>
    <configuration name="cycles" value="11"/>
  </readpath>
  
  <writepath name="rdmrdmoverarm">
    <processor name="ARM"/>
    <txbuf name="rdm"/>
    <hw_channel name="armbus"/>
    <chbuf name="rdm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="1"/>  <!-- not confirmed -->
  </writepath>
  
  <readpath name="rdmrdmoverarm">
    <processor name="ARM"/>
    <chbuf name="rdm"/>
    <hw_channel name="armbus"/>
    <rxbuf name="rdm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="1"/>  <!-- not confirmed -->
  </readpath>
  
  <writepath name="armrdmddm">
    <processor name="ARM"/>
    <txbuf name="rdm"/>
    <hw_channel name="ahb0"/>
    <hw_channel name="dma"/>
    <chbuf name="ddm"/>
    <configuration name="delay" value="48"/> <!-- not confirmed -->
    <configuration name="cycles" value="1"/> <!-- not confirmed -->
  </writepath>

  <readpath name="armddmrdm">
    <processor name="ARM"/>
    <chbuf name="ddm"/>
    <hw_channel name="dma"/>
    <hw_channel name="ahb0"/>
    <rxbuf name="rdm"/>
    <configuration name="delay" value="48"/> <!-- not confirmed -->
    <configuration name="cycles" value="1"/> <!-- not confirmed -->
  </readpath>

  <writepath name="dxmdxm">
    <processor name="ARM"/>
    <txbuf name="dxm"/>
    <hw_channel name="ahb1"/>
    <chbuf name="dxm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="16"/>  <!-- not confirmed -->
  </writepath>

  <readpath name="dxmdxm">
    <processor name="ARM"/>
    <chbuf name="dxm"/>
    <hw_channel name="ahb1"/>
    <rxbuf name="dxm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="16"/>  <!-- not confirmed -->
  </readpath>

  <writepath name="rdmrdmoverahb">
    <processor name="ARM"/>
    <txbuf name="rdm"/>
    <hw_channel name="ahb0"/>
    <chbuf name="rdm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="2"/>  <!-- not confirmed -->
  </writepath>
  
  <readpath name="rdmrdmoverahb">
    <processor name="ARM"/>
    <chbuf name="rdm"/>
    <hw_channel name="ahb0"/>
    <rxbuf name="rdm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="2"/>  <!-- not confirmed -->
  </readpath>

  <writepath name="dxmddm">
    <processor name="ARM"/>
    <txbuf name="dxm"/>
    <hw_channel name="ahb1"/>
    <hw_channel name="dma"/>
    <chbuf name="ddm"/>
    <configuration name="delay" value="48"/> <!-- not confirmed -->
    <configuration name="cycles" value="1"/>  <!-- not confirmed -->
  </writepath>
  
  <readpath name="ddmdxm">
    <processor name="ARM"/>
    <chbuf name="ddm"/>
    <hw_channel name="dma"/>
    <hw_channel name="ahb1"/>
    <rxbuf name="dxm"/>
    <configuration name="delay" value="48"/> <!-- not confirmed -->
    <configuration name="cycles" value="1"/>  <!-- not confirmed -->
  </readpath>

  <!-- magic paths -->
  <writepath name="ddmdxm">
    <processor name="MAGIC"/>
    <txbuf name="ddm"/>
    <hw_channel name="dma"/>
    <hw_channel name="ahb1"/>
    <chbuf name="dxm"/>
    <configuration name="delay" value="8"/> <!-- not confirmed -->
    <configuration name="cycles" value="1"/>  <!-- not confirmed -->
  </writepath>
  
  <readpath name="dxmddm">
    <processor name="MAGIC"/>
    <chbuf name="dxm"/>
    <hw_channel name="ahb1"/>
    <hw_channel name="dma"/>
    <rxbuf name="ddm"/>
    <configuration name="delay" value="8"/> <!-- not confirmed -->
    <configuration name="cycles" value="1"/>  <!-- not confirmed -->
  </readpath>
  
  <writepath name="ddmddm">
    <processor name="MAGIC"/>
    <txbuf name="ddm"/>
    <hw_channel name="magicbus"/>
    <chbuf name="ddm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="1"/>  <!-- not confirmed -->
  </writepath>
  
  <readpath name="ddmddm">
    <processor name="MAGIC"/>
    <chbuf name="ddm"/>
    <hw_channel name="magicbus"/>
    <rxbuf name="ddm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="1"/>  <!-- not confirmed -->
  </readpath>
  
  <writepath name="magicddmrdm">
    <processor name="MAGIC"/>
    <txbuf name="ddm"/>
    <hw_channel name="dma"/>
    <hw_channel name="ahb0"/>
    <chbuf name="rdm"/>
    <configuration name="delay" value="16"/>
    <configuration name="cycles" value="1"/>
  </writepath>

  <readpath name="magicrdmddm">
    <processor name="MAGIC"/>
    <chbuf name="rdm"/>
    <hw_channel name="ahb0"/>
    <hw_channel name="dma"/>
    <rxbuf name="ddm"/>
    <configuration name="delay" value="6"/>
    <configuration name="cycles" value="1"/>
  </readpath>

  <!-- ssc paths -->
  <writepath name="sscregdxm">
    <processor name="SSC"/>
    <txbuf name="sscreg"/>
    <hw_channel name="ahb1"/>
    <chbuf name="dxm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="4"/>  <!-- not confirmed -->
  </writepath>

  <readpath name="dxmsscreg">
    <processor name="SSC"/>
    <chbuf name="dxm"/>
    <hw_channel name="ahb1"/>
    <rxbuf name="sscreg"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="4"/>  <!-- not confirmed -->
  </readpath>

  <writepath name="sscregrdm">
    <processor name="SSC"/>
    <txbuf name="sscreg"/>
    <hw_channel name="ahb0"/>
    <chbuf name="rdm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="4"/>  <!-- not confirmed -->
  </writepath>

  <readpath name="rdmsscreg">
    <processor name="SSC"/>
    <chbuf name="rdm"/>
    <hw_channel name="ahb0"/>
    <rxbuf name="sscreg"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="4"/>  <!-- not confirmed -->
  </readpath>

  <writepath name="sscregddm">
    <processor name="SSC"/>
    <txbuf name="sscreg"/>
    <hw_channel name="ahb2"/>
    <chbuf name="ddm"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="4"/>  <!-- not confirmed -->
  </writepath>

  <readpath name="ddmsscreg">
    <processor name="SSC"/>
    <chbuf name="ddm"/>
    <hw_channel name="ahb2"/>
    <rxbuf name="sscreg"/>
    <configuration name="delay" value="0"/> <!-- not confirmed -->
    <configuration name="cycles" value="4"/>  <!-- not confirmed -->
  </readpath>
</architecture>
