=== wendy48/ES2016_14353395/dol/schema/mapping.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:map="http://www.tik.ee.ethz.ch/~shapes/schema/MAPPING" targetNamespace="http://www.tik.ee.ethz.ch/~shapes/schema/MAPPING" elementFormDefault="qualified">
  <xsd:include schemaLocation="generics.xsd"/>

  <xsd:element name="mapping">
    <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="variable" type="map:variable" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="function" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="iterator" type="map:generaliterator" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="binding" type="map:binding" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="schedule" type="map:schedule" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="binding">
    <xsd:sequence>
      <xsd:element name="append" type="map:append" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>
  
  <xsd:complexType name="computation">
    <xsd:complexContent>
      <xsd:extension base="map:binding">
        <xsd:sequence>
          <xsd:element name="process" type="map:resource" minOccurs="1" maxOccurs="1"/>
          <xsd:element name="processor" type="map:resource" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="communication">
    <xsd:complexContent>
      <xsd:extension base="map:binding">
        <xsd:sequence>
          <xsd:element name="sw_channel" type="map:resource" minOccurs="1" maxOccurs="1"/>
          <xsd:element name="writepath" type="map:resource" minOccurs="1" maxOccurs="1"/>
          <xsd:element name="readpath" type="map:resource" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="schedule">
    <xsd:sequence>
      <xsd:element name="append" type="map:append" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="resource" type="map:resource"/>
      <xsd:element name="origin" type="map:configuredresource" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="configuration" type="map:configuration" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="type" use="required">
      <xsd:simpleType>
        <xsd:restriction base="xsd:string">
          <xsd:enumeration value="static"/>
          <xsd:enumeration value="fixedpriority"/>
          <xsd:enumeration value="fifo"/>
          <xsd:enumeration value="tdma"/>
          <xsd:enumeration value="roundrobin"/>
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:attribute>
  </xsd:complexType>

  <xsd:complexType name="resource">
    <xsd:sequence>
      <xsd:element name="append" type="map:append" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="configuredresource">
    <xsd:sequence>
      <xsd:element name="append" type="map:append" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="configuration" type="map:configuration" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="generaliterator">
    <xsd:complexContent>
      <xsd:extension base="map:iterator">
        <xsd:sequence>
          <xsd:element name="iterator" type="map:generaliterator" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="binding" type="map:binding" minOccurs="0" maxOccurs="unbounded"/>
          <xsd:element name="schedule" type="map:schedule" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

</xsd:schema>

=== wendy48/ES2016_14353395/.local/share/Trash/files/dol/examples/example1/map_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/MAPPING" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/MAPPING     http://www.tik.ee.ethz.ch/~shapes/schema/mapping.xsd" name="example1_map_1">
 
<binding name="generator" xsi:type="computation">
	<process name="generator" />
	<processor name="sim1" />
</binding>
<binding name="consumer" xsi:type="computation">
	<process name="consumer" />
	<processor name="sim1" />
</binding>
<binding name="square" xsi:type="computation">
	<process name="square" />
	<processor name="sim1" />
</binding>
</mapping>

=== wendy48/ES2016_14353395/dol/examples/mapping/wfsmapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/MAPPING" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/MAPPING
http://www.tik.ee.ethz.ch/~shapes/schema/mapping.xsd" name="WFSonVSP"> 

  <!-- process bindings -->
  <binding name="binding_src_0" xsi:type="computation">
    <process name="src_0"/>
    <processor name="ARM"/>
  </binding>

  <binding name="binding_src_1" xsi:type="computation">
    <process name="src_1"/>
    <processor name="ARM"/>
  </binding>

  <binding name="binding_control" xsi:type="computation">
    <process name="control"/>
    <processor name="ARM"/>
  </binding>

  <binding name="binding_conv_0_0" xsi:type="computation">
    <process name="convolver_wrapper_0_0"/>
    <processor name="MAGIC"/>
  </binding>

  <binding name="binding_conv_0_1" xsi:type="computation">
    <process name="convolver_wrapper_0_1"/>
    <processor name="MAGIC"/>
  </binding>

  <binding name="binding_conv_1_0" xsi:type="computation">
    <process name="convolver_wrapper_1_0"/>
    <processor name="MAGIC"/>
  </binding>

  <binding name="binding_conv_1_1" xsi:type="computation">
    <process name="convolver_wrapper_1_1"/>
    <processor name="MAGIC"/>
  </binding>

  <binding name="binding_sum_0" xsi:type="computation">
    <process name="sum_0"/>
    <processor name="MAGIC"/>
  </binding>

  <binding name="binding_sum_1" xsi:type="computation">
    <process name="sum_1"/>
    <processor name="MAGIC"/>
  </binding>

  <binding name="binding_ls_0" xsi:type="computation">
    <process name="ls_0"/>
    <processor name="MAGIC"/>
  </binding>

  <binding name="binding_ls_1" xsi:type="computation">
    <process name="ls_1"/>
    <processor name="MAGIC"/>
  </binding>

  <!-- channel bindings -->
  <binding name="binding_src_conv_0_0" xsi:type="communication">
    <sw_channel name="fifo_src_conv_0_0"/>
    <writepath name="ddmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_src_conv_0_1" xsi:type="communication">
    <sw_channel name="fifo_src_conv_0_1"/>
    <writepath name="ddmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_src_conv_1_0" xsi:type="communication">
    <sw_channel name="fifo_src_conv_1_0"/>
    <writepath name="ddmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_src_conv_1_1" xsi:type="communication">
    <sw_channel name="fifo_src_conv_1_1"/>
    <writepath name="ddmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_ctrl_conv_0_0" xsi:type="communication">
    <sw_channel name="fifo_ctrl_conv_0_0"/>
    <writepath name="armrdmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_ctrl_conv_0_1" xsi:type="communication">
    <sw_channel name="fifo_ctrl_conv_0_1"/>
    <writepath name="armrdmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_ctrl_conv_1_0" xsi:type="communication">
    <sw_channel name="fifo_ctrl_conv_1_0"/>
    <writepath name="armrdmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_ctrl_conv_1_1" xsi:type="communication">
    <sw_channel name="fifo_ctrl_conv_1_1"/>
    <writepath name="armrdmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_conv_sum_0_0" xsi:type="communication">
    <sw_channel name="fifo_conv_sum_0_0"/>
    <writepath name="ddmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_conv_sum_0_1" xsi:type="communication">
    <sw_channel name="fifo_conv_sum_0_1"/>
    <writepath name="ddmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_conv_sum_1_0" xsi:type="communication">
    <sw_channel name="fifo_conv_sum_1_0"/>
    <writepath name="ddmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_conv_sum_1_1" xsi:type="communication">
    <sw_channel name="fifo_conv_sum_1_1"/>
    <writepath name="ddmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_sum_ls_0" xsi:type="communication">
    <sw_channel name="fifo_sum_ls_0"/>
    <writepath name="ddmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <binding name="binding_sum_ls_1" xsi:type="communication">
    <sw_channel name="fifo_sum_ls_1"/>
    <writepath name="ddmddm"/>
    <readpath name="ddmddm"/>
  </binding>

  <!-- schedules -->
  <schedule name="armschedule" type="static">
    <resource name="ARM"/>
    <origin name="control">
      <configuration name="priority" value="1"/>
    </origin>
  </schedule>

  <schedule name="magicschedule" type="static">
    <resource name="MAGIC"/>
    <origin name="src_0">
      <configuration name="priority" value="0"/>
    </origin>
    <origin name="src_1">
      <configuration name="priority" value="1"/>
    </origin>
    <origin name="convolver_wrapper_0_0">
      <configuration name="priority" value="2"/>
    </origin>
    <origin name="convolver_wrapper_0_1">
      <configuration name="priority" value="3"/>
    </origin>
    <origin name="convolver_wrapper_1_0">
      <configuration name="priority" value="4"/>
    </origin>
    <origin name="convolver_wrapper_1_1">
      <configuration name="priority" value="5"/>
    </origin>
    <origin name="sum_0">
      <configuration name="priority" value="6"/>
    </origin>
    <origin name="sum_1">
      <configuration name="priority" value="7"/>
    </origin>
    <origin name="ls_0">
      <configuration name="priority" value="8"/>
    </origin>
    <origin name="ls_1">
      <configuration name="priority" value="9"/>
    </origin>
  </schedule>
  
  <schedule name="ahb0schedule" type="fifo">
    <resource name="ahb0"/>
  </schedule>

  <schedule name="dmaschedule" type="fifo">
    <resource name="dma"/>
  </schedule>

  <schedule name="magicbusschedule" type="fifo">
    <resource name="magicbus"/>
  </schedule>
</mapping>

=== wendy48/ES2016_14353395/dol/examples/examplecell/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.tik.ee.ethz.ch/~shapes/schema/MAPPING"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tik.ee.ethz.ch/~shapes/schema/MAPPING
                      http://www.tik.ee.ethz.ch/~shapes/schema/mapping.xsd"
  name="examplecell on Cell">

  <binding name="binding_generator" xsi:type="computation">
    <process name="generator"/>
    <processor name="ppu"/>
  </binding>
  
  <binding name="binding_square_0" xsi:type="computation">
    <process name="square_0">
    </process>
    <processor name="spu_4"/>
  </binding>

  <binding name="binding_square_1" xsi:type="computation">
    <process name="square_1">
    </process>
    <processor name="spu_1"/>
  </binding>
  
  <binding name="binding_square_2" xsi:type="computation">
    <process name="square_2">
    </process>
    <processor name="spu_2"/>
  </binding>
  
  <binding name="binding_square_3" xsi:type="computation">
    <process name="square_3">
    </process>
    <processor name="spu_3"/>
  </binding>
  
  <binding name="binding_square_4" xsi:type="computation">
    <process name="square_4">
    </process>
    <processor name="spu_4"/>
  </binding>

  <binding name="binding_square_5" xsi:type="computation">
    <process name="square_5">
    </process>
    <processor name="spu_5"/>
  </binding>
  
  <binding name="binding_square_6" xsi:type="computation">
    <process name="square_6">
    </process>
    <processor name="spu_1"/>
  </binding>
  
  <binding name="binding_square_7" xsi:type="computation">
    <process name="square_7">
    </process>
    <processor name="spu_2"/>
  </binding>
  
  <binding name="binding_square_8" xsi:type="computation">
    <process name="square_8">
    </process>
    <processor name="spu_3"/>
  </binding>
  
  <binding name="binding_consumer" xsi:type="computation">
    <process name="consumer"/>
    <processor name="spu_0"/>
  </binding>
</mapping>
